### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by subnut** [khuedoan/dotfiles#3]
The procedure you mentioned doesnot work. Shows URL error in an html file that gets downloaded instead

**Comment by khuedoan** [comment]
Fixed it and updated the document, please re-open if the same issue still exist.

**Comment by subnut** [comment]
hey there! sorry for the late reply.... was a bit busy lately 😅
i tried `./install,sh --dotfiles --aur-helper --packages`
and when everything finished, i ran the command `bspwm` (without sudo, i.e. as default user)
yes, the wallpaper loads..... but is blurred by compton
then i tried `Win + Enter`
the terminal didn't come up. instead, the whole screen flashed red alongwith a hardware BEEP sound
none of the key combinations you showed in your README worked

Dunno why this is happening.... i just want a cool Arch desktop like yours!

**Comment by khuedoan** [comment]
Sorry I forgot to mention, that was the [slock](https://github.com/khuedoan98/slock) lock screen, just type your password and press Enter :smile:

I added a "Enter your password" message to the lockscreen for better UX for new user.
You can update the change by running:

`dotfiles pull`

Then start Xorg again:

`startx`

Note that you may need to change your default shell to Zsh:

`chsh -s /bin/zsh`

If you don't want this just comment out the `slock -m "Enter your password" &` line in `.xinitrc` and it will not lock the screen when starting Xorg.

It was there in the first place because I use [automatic login to virtual console](https://wiki.archlinux.org/index.php/getty#Automatic_login_to_virtual_console). I'm planning to remove this when I have a better solution because it is a little bit less secure.

**Comment by subnut** [comment]
Oh! That solved it. Thank you very very much!
